config/routes.rb
Rails.application.routes.draw do

  resources :buy_plans, only: [:new, :create, :edit]
  resources :buy_books, only: [:new, :create, :edit]
  resources :sshkeys
  get '/buy_books/new/:id', to: 'buy_books#new'
  get '/buy_books/edit', to: 'buy_books#edit'
  get '/buy_plans/new/:id', to: 'buy_plans#new'
  get '/buy_plans/edit', to: 'buy_plans#edit'

  scope module: 'admin' do
     resources :plans, :books, :cards, :referrals, :keys
  end

  get 'pages/webhook', to: 'pages#webhook'
  post 'pages/webhook', to: 'pages#webhook'
  get 'pages/page0'
  get 'pages/page1'
  get 'pages/page2'
  get 'pages/products'

  root :to => 'pages#index'

  get 'admin', to: 'admin/pages#index'

  devise_for :admins
  devise_for :users
  
end

app/models/referral.rb
class Referral < ApplicationRecord
end

app/controllers/admin/referrals_controller.rb
class Admin::ReferralsController < ApplicationController
  before_action :set_referral, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /referrals
  # GET /referrals.json
  def index
    @referrals = Referral.all
  end

  # GET /referrals/1
  # GET /referrals/1.json
  def show
  end

  # GET /referrals/new
  def new
    @referral = Referral.new
  end

  # GET /referrals/1/edit
  def edit
  end

  # POST /referrals
  # POST /referrals.json
  def create
    @referral = Referral.new(referral_params)

    respond_to do |format|
      if @referral.save
        format.html { redirect_to @referral, notice: 'Referral was successfully created.' }
        format.json { render :show, status: :created, location: @referral }
      else
        format.html { render :new }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /referrals/1
  # PATCH/PUT /referrals/1.json
  def update
    respond_to do |format|
      if @referral.update(referral_params)
        format.html { redirect_to @referral, notice: 'Referral was successfully updated.' }
        format.json { render :show, status: :ok, location: @referral }
      else
        format.html { render :edit }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referrals/1
  # DELETE /referrals/1.json
  def destroy
    @referral.destroy
    respond_to do |format|
      format.html { redirect_to referrals_url, notice: 'Referral was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_referral
      @referral = Referral.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def referral_params
      params.require(:referral).permit(:OldEmail, :NewEmail, :old_id, :new_id, :bonuspaid)
    end
end

app/views/admin/referrals/_form.html.erb
<%= form_for(referral) do |f| %>
  <% if referral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(referral.errors.count, "error") %> prohibited this referral from being saved:</h2>

      <ul>
      <% referral.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :OldEmail %>
    <%= f.text_field :OldEmail %>
  </div>

  <div class="field">
    <%= f.label :NewEmail %>
    <%= f.text_field :NewEmail %>
  </div>

  <div class="field">
    <%= f.label :old_id %>
    <%= f.number_field :old_id %>
  </div>

  <div class="field">
    <%= f.label :new_id %>
    <%= f.number_field :new_id %>
  </div>

  <div class="field">
    <%= f.label :bonuspaid %>
    <%= f.check_box :bonuspaid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/referrals/edit.html.erb
<h1>Editing Referral</h1>

<%= render 'form', referral: @referral %>

<%= link_to 'Show', @referral %> |
<%= link_to 'Back', referrals_path %>

app/views/admin/referrals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Referrals</h1>

<table>
  <thead>
    <tr>
      <th>Oldemail</th>
      <th>Newemail</th>
      <th>Old id</th>
      <th>New id</th>
      <th>Bonuspaid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @referrals.each do |referral| %>
      <tr>
        <td><%= referral.OldEmail %></td>
        <td><%= referral.NewEmail %></td>
        <td><%= referral.old_id %></td>
        <td><%= referral.new_id %></td>
        <td><%= referral.bonuspaid %></td>
        <td><%= link_to 'Show', referral %></td>
        <td><%= link_to 'Edit', edit_referral_path(referral) %></td>
        <td><%= link_to 'Destroy', referral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Referral', new_referral_path %>

app/views/admin/referrals/new.html.erb
<h1>New Referral</h1>

<%= render 'form', referral: @referral %>

<%= link_to 'Back', referrals_path %>

app/views/admin/referrals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oldemail:</strong>
  <%= @referral.OldEmail %>
</p>

<p>
  <strong>Newemail:</strong>
  <%= @referral.NewEmail %>
</p>

<p>
  <strong>Old id:</strong>
  <%= @referral.old_id %>
</p>

<p>
  <strong>New id:</strong>
  <%= @referral.new_id %>
</p>

<p>
  <strong>Bonuspaid:</strong>
  <%= @referral.bonuspaid %>
</p>

<%= link_to 'Edit', edit_referral_path(@referral) %> |
<%= link_to 'Back', referrals_path %>