config/routes.rb
Rails.application.routes.draw do

  resources :buy_plans, only: [:new, :create, :edit]
  resources :buy_books, only: [:new, :create, :edit]
  resources :sshkeys
  get '/buy_books/new/:id', to: 'buy_books#new'
  get '/buy_books/edit', to: 'buy_books#edit'
  get '/buy_plans/new/:id', to: 'buy_plans#new'
  get '/buy_plans/edit', to: 'buy_plans#edit'

  scope module: 'admin' do
     resources :plans, :books, :cards, :referrals, :keys
  end

  get 'pages/webhook', to: 'pages#webhook'
  post 'pages/webhook', to: 'pages#webhook'
  get 'pages/page0'
  get 'pages/page1'
  get 'pages/page2'
  get 'pages/products'

  root :to => 'pages#index'

  get 'admin', to: 'admin/pages#index'

  devise_for :admins
  devise_for :users
  
end

app/models/plan.rb
class Plan < ApplicationRecord
    has_many :users, through: :buy_plans
    has_many :buy_plans
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:stripe_id, :price, :period)
    end
end

app/views/admin/plans/_form.html.erb
<%= form_for(plan) do |f| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stripe_id %>
    <%= f.text_field :stripe_id %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :period %>
    <%= f.datetime_select :period %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/admin/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Stripeid</th>
      <th>Price</th>
      <th>Period</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.stripe_id %></td>
        <td><%= plan.price %></td>
        <td><%= plan.period %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/admin/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>

app/views/admin/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stripeid:</strong>
  <%= @plan.stripe_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @plan.price %>
</p>

<p>
  <strong>Period:</strong>
  <%= @plan.period %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>