config/routes.rb
Rails.application.routes.draw do

  resources :buy_plans, only: [:new, :create, :edit]
  resources :buy_books, only: [:new, :create, :edit]
  resources :sshkeys
  get '/buy_books/new/:id', to: 'buy_books#new'
  get '/buy_books/edit', to: 'buy_books#edit'
  get '/buy_plans/new/:id', to: 'buy_plans#new'
  get '/buy_plans/edit', to: 'buy_plans#edit'

  scope module: 'admin' do
     resources :plans, :books, :cards, :referrals, :keys
  end

  get 'pages/webhook', to: 'pages#webhook'
  post 'pages/webhook', to: 'pages#webhook'
  get 'pages/page0'
  get 'pages/page1'
  get 'pages/page2'
  get 'pages/products'

  root :to => 'pages#index'

  get 'admin', to: 'admin/pages#index'

  devise_for :admins
  devise_for :users
  
end

app/controllers/admin/keys_controller.rb
class Admin::KeysController < ApplicationController
  before_action :set_key, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  def index
	@keys=Sshkey.all
  end

  # GET /keys/1
  # GET /keys/1.json
  def show
  end

  # GET /keys/new
  def new
    @key = Sshkey.new
  end

  # GET /keys/1/edit
  def edit
  end

  # POST /keys
  # POST /keys.json
  def create
    respond_to do |format|
      if @key.save
        format.html { redirect_to @key, notice: 'Sshkey was successfully created.' }
        format.json { render :show, status: :created, location: @key }
      else
        format.html { render :new }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keys/1
  # PATCH/PUT /keys/1.json
  def update
    respond_to do |format|
      if @key.update(key_params)
        format.html { redirect_to @key, notice: 'Sshkey was successfully updated.' }
        format.json { render :show, status: :ok, location: @key }
      else
        format.html { render :edit }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keys/1
  # DELETE /keys/1.json
  def destroy
    @key.destroy
    respond_to do |format|
      format.html { redirect_to keys_url, notice: 'Sshkey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_key
      @key = Sshkey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def key_params
      params.require(:key).permit(:user_id, :key)
    end
end

app/views/admin/keys/_form.html.erb
<%= form_for(key) do |f| %>
  <% if key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(key.errors.count, "error") %> prohibited this key from being saved:</h2>

      <ul>
      <% key.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %>
    <%= f.text_field :key %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/keys/edit.html.erb
<h1>Editing Sshkey</h1>

<%= render 'form', key: @key %>

<%= link_to 'Show', @key %> |
<%= link_to 'Back', keys_path %>

app/views/admin/keys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>SSH keys</h1>

<table>
  <thead>
    <tr>
      <th>User id</th>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keys.each do |key| %>
      <tr>
        <td><%= key.user_id %></td>
        <td><%= key.key %></td>
        <td><%= link_to 'Show', key_path(key) %></td>
        <td><%= link_to 'Edit', edit_key_path(key) %></td>
        <td><%= link_to 'Destroy', key_path(key), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sshkey', new_key_path %>

app/views/admin/keys/new.html.erb
<h1>New SSH key</h1>

<%= render 'form', key: @key %>

<%= link_to 'Back', keys_path %>

app/views/admin/keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User id:</strong>
  <%= @key.user_id %>
</p>

<p>
  <strong>Key:</strong>
  <%= @key.key %>
</p>

<%= link_to 'Edit', edit_key_path(@key) %> |
<%= link_to 'Back', keys_path %>